CREATE TABLE MOCK (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    METHOD VARCHAR(100) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL,
    DAT_CREATION TIMESTAMP NOT NULL,
    DAT_UPDATE TIMESTAMP NOT NULL
);

CREATE TABLE MOCK_DETAILS (
    ID SERIAL PRIMARY KEY,
    PAYLOAD TEXT,
    WORKFLOW_SCRIPT VARCHAR(25),
    METADATA TEXT,
    DAT_CREATION TIMESTAMP NOT NULL,
    DAT_UPDATE TIMESTAMP NOT NULL,
    MOCK_ID INT REFERENCES MOCK(ID)
);
