spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/mock
    username: mock-root
    password: mock123
  jpa:
    show_sql: true
    format_sql: true
  flyway:
    baselineOnMigrate: true
    locations: classpath:database/migrations