spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mock
    username: mock-root
    password: mock123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show_sql: true
      format_sql: true